### ISSUE TITLE
[FR] Setting to use other forward-zone entries even if "." exists

### ISSUE THREAD

**Issue by alxndr42** [NLnetLabs/unbound#1355]
**Current behavior**

When a `forward-zone` with the name `"."` is configured, Unbound ignores all other `forward-zone` entries.

**Describe the desired feature**

Maybe a setting that makes Unbound use `forward-zone` entries for matching domains/prefixes before using the `"."` entry?

**Potential use-case**

This would be useful for DNS censorship situations, to direct queries for targeted domains to different upstream servers.

**Comment by wcawijngaards** [comment]
This is already the case. Unbound uses the `forward-zone` and `stub-zone` that is closest to the name that is looked up. It is possible to have any number of `forward-zone` and `stub-zone` entries. Apart from high level ones, more specific entries can be used to direct traffic for those zones.

It is also possible to have `auth-zone` entries, also the closest to the name looked up is used. There used to be a bug where the combination of the different types of entries and that the name closest is used, was not closest, but that should be fixed now.

For having fallback data, apart from `auth-zone`, it is possible to have `local-zone` entries. The `local-zone` entries are processed before the cache is consulted or the recursive lookups are performed, and are used to filter and have direct answers with data. The `local-zone` entries can be used to provide the direct data for a name. The `forward-zone` and `stub-zone` entries direct queries to different upstream servers.

**Comment by alxndr42** [comment]
> Unbound uses the forward-zone and stub-zone that is closest to the name that is looked up.

That was my expectation too, but it's not the behavior I'm seeing (using Unbound 1.19.2).

My `forward-zone` configuration looks like this (censored domain replaced):

```
forward-zone:
    name: "censored.example.com"
    forward-tls-upstream: yes
    forward-addr: 185.71.138.138@853#wikimedia-dns.org
    forward-addr: 2001:67c:930::1@853#wikimedia-dns.org

forward-zone:
    name: "."
    forward-tls-upstream: yes
    forward-addr: 9.9.9.9@853#dns.quad9.net
    forward-addr: 2620:fe::9@853#dns.quad9.net
```

When I run `dig @127.0.0.1 censored.example.com`, I'm still getting a `SERVFAIL` (i.e. Quad9 is not resolving the domain).

**Comment by wcawijngaards** [comment]
For me this piece of config is not a problem, it works to send the queries to the forward addrs for the censored.example.com zone. The server there does not respond to the tls upstream, nicely, it gives handshakre failures for the TLS, with a certificate failure. No certificate used perhaps.

Maybe try it without the tls upstream, and config `verbosity: 5` to get additional details. For me this works to send the traffic to the more specific destination.

**Comment by alxndr42** [comment]
One other thing I tried is to use only the Wikimedia resolvers (for `"."`), which works as expected, i.e. the domain is resolved.

When setting `verbosity: 5`, I can see in the logs that Unbound actually does query Wikimedia first, and receives a response (`incoming scrubbed packet` with A records), but then sends a ton of additional queries to the Quad9 servers. Eventually, this appears in the logs: `debug: rrset failed to verify: all signatures are bogus`

I'm guessing mixing responses from multiple upstreams somehow doesn't work with DNSSEC?

**Comment by wcawijngaards** [comment]
Did you set it to `forward-first: yes`, if so that is the expected behaviour. But it is caused by the server that is configured not responding usefully. That looks like what needs to work for the issue.

**Comment by wcawijngaards** [comment]
But of course, that signature bogus error may be happening as the more specific server makes content for those domains, but the DNSSEC signatures are for the content, that Unbound is fetching from the "." server. The chain of trust then is attempted to be built towards the more specific content, but this then fails, since it is replaced content. In that sense the more specific server is not giving access to denied content, but access to different content, and thus it fails DNSSEC validation. The option `domain-insecure: "censored.example.com"` is needed, and it stops the DNSSEC validation problem. It is also possible to turn off dnssec validation for everything. The `domain-insecure: "example.net"` option can be given several times, once for every more specific `forward-zone` that has been created, so as to ignore the DNSSEC failures where the content from that does not match the DNSSEC validation.

**Comment by alxndr42** [comment]
I haven't changed `forward-first`, so it should still be `no`.

The `domain-insecure` setting did cause the domain to be resolved! 🎉 (The actual domain used for testing has no DNSSEC, which may have contributed to the problem.)

Overall this seems like a somewhat brittle setup, though. It's probably safer to stick to a single set of upstream resolvers.

Either way, thank you for your help and insight!

**Comment by wcawijngaards** [comment]
Other people have used more specific forwards, and stubs, with `domain-insecure`, in production, so it can work okay. It is nice to hear that the issue is solved!

**Comment by sthen** [comment]
I think there's still something fishy with this. If I configure a forward-zone for "." and a more-specific forward-zone (by way of example let's say for "com") with forward-first: yes, and the forwarder for "com" fails, unbound tries resolving names under com via the forwarder for "."

(This could have some practical use; one might want to use a public or ISP forwarder for most queries, but do a recursive lookup for queries in RBL zones to avoid rate limits - if this fallback didn't happen, it would be possible to specify a dummy unreachable address e.g. 0.0.0.0 as forwarder, to achieve this).

**Comment by gthess** [comment]
Forward zones can fallback to less specific ones when there is a resolution error with `forward-first: yes`.
If the `.` forward zone has enabled fallback, then it will fallback to recursion.
There is no way to fallback from a more specific forward-zone all the way to recursion in one step, Unbound will try all the configured options.

For the RBL zones example, wouldn't [stub zones](https://unbound.docs.nlnetlabs.nl/en/latest/manpages/unbound.conf.html#stub-zone-options) address that behavior?

**Comment by sthen** [comment]
Stub zones don't really work for this situation, you would need to monitor for NS changes in the domain and rewrite the relevant part of unbound's configuration. Seems the only real workaround would be to forward to a separate instance running locally configured to only do recursion, which works but is a bit unwieldy.

If this (resolution failure falls back to a less specific forward-zone) is definitely the intended behaviour, it's probably worth a mention in `Forward zone options` in unbound.conf(5), e.g. possibly like this, to make it clear

```
@@UAHL@unbound.conf.forward@forward-first@@: *<yes or no>*
    If a forwarded query is met with a SERVFAIL error, and this option is
    enabled, Unbound will fall back to a less specific
    :ref:`forward-addr<unbound.conf.forward.name>` if present,
    otherwise to normal recursive resolution for this
    query as if no query forwarding had been specified.
```

**Comment by gthess** [comment]
I like the suggestion for the documentation update -> https://github.com/NLnetLabs/unbound/commit/09d352b91726a333242c608a6a90def4713ed214
