### ISSUE TITLE
Jump in num.answer.rcode.refused and num.answer.rcode.nxdomain after upgrading from 1.9.6 to 1.11.0 on Centos 8

### ISSUE THREAD

**Issue by leoleovich** [NLnetLabs/unbound#289]
Hi there,
We are testing latest version of unbound and right away we see a strange jump in these 2 metrics:
![image](https://user-images.githubusercontent.com/4749052/89999797-3a001100-dc87-11ea-9aeb-18ef9ebbb441.png)
We are positive it's not an actual increase of refused because we also monitor queries via dnstap and there is no jump:
![image](https://user-images.githubusercontent.com/4749052/90004000-d547b500-dc8c-11ea-8fc9-d8d6fe479a3d.png)

As you see numbers on these 2 graphs match before the upgrade to 1.11 and the second graph (dnstap) continues the same trend after the upgrade.
In addition, with tcpdump we were unable to find any valid increase in number of refused nor nxdomains.

We see this across all upgraded servers.
Build spec was not changed compare to 1.9.6.

Any known/expected change in calculating refused/nxdomains counters?
Thanks in advance!

**Comment by leoleovich** [comment]
We also see a counter jump on servers which never had "refused":
![image](https://user-images.githubusercontent.com/4749052/90003367-e04e1580-dc8b-11ea-96ad-228a9c166f18.png)
And again, there are no REFUSED seen via dnstap.

**Comment by ralphdolmans** [comment]
Thanks for reporting this and sharing the graphs!

I think we have found the issue. After changes in Unbound 1.10 some of the stats were incremented twice per query, this was amongst others the case for REFUSED answers. This should be fixed in this commit: https://github.com/NLnetLabs/unbound/compare/8b05dcdf8c3f...e6ebabc0cc49. Please give it a try.

I do not (yet) have an explanation for the last graph. Do you one these machines also not observe REFUSED answers in dnstap and/or tcpdump?

**Comment by leoleovich** [comment]
> I do not (yet) have an explanation for the last graph. Do you one these machines also not observe REFUSED answers in dnstap and/or tcpdump?

Correct, `dnstap` does not show **ANY** REFUSED on the hosts from the last graph. And there were no REFUSED before the update.
Let me try to test your commit and see if it helps.

**Comment by leoleovich** [comment]
Hi @ralphdolmans,
Thanks for your patch again. It definitely helped! In most cases numbers are back to the 1.9.6 levels:
![image](https://user-images.githubusercontent.com/4749052/90978898-0192e980-e549-11ea-9139-952b15e50896.png)

However, the servers which previously have not had any REFUSED still have some very small number (~10 per minute):
![image](https://user-images.githubusercontent.com/4749052/90978974-8847c680-e549-11ea-9673-5c8e7a100c7e.png)

I checked `dnstap` again - there is not a single REFUSED.

**Comment by leoleovich** [comment]
Other than that small thing we are good to close it. All other metrics look very good!
