### ISSUE TITLE
Local hostnames are not resolved by unbound

### ISSUE THREAD

**Issue by viktak** [NLnetLabs/unbound#900]
I'm not sure if this is a bug/feature or (most likely) my lack of understanding how unbound works:

My setup is as follows:
I have a RPi setup with pi-hole and unbound working together for years - no issues.
I would like to use a domain of mine (viktak.cc) to access my local network using Nginx Proxy Manager. I set it all up, and all the proxy hosts work fine (i.e. when I type https://notes.viktak.cc I get to the service I want).
The problem is that this works ONLY on the PC I set this all up (in this case, it's a Windows 11 box). On the whole home network I get `DNS address could not be found` in the browser. Also, even on the Windows box, wher it works in the browser, when I try to ping any of the proxy hosts I get: `Ping request could not find host notes.viktak.cc. Please check the name and try again.`

If I disable unbound on the RPi, and use any public DNS resolver, the problem goes away, i.e. on any computer on the home network I can ping and browse to the proxy hosts successfully.

Any idea what might be the problem?

Here is `/etc/unbound/unbound.conf.d/pi-hole.conf`:
```
pi@pihole:~ $ cat /etc/unbound/unbound.conf.d/pi-hole.conf
server:
    # If no logfile is specified, syslog is used
    logfile: "/var/log/unbound/unbound.log"
    verbosity: 0

    interface: 127.0.0.1
    port: 5335
    do-ip4: yes
    do-udp: yes
    do-tcp: yes

    # May be set to yes if you have IPv6 connectivity
    do-ip6: no

    # You want to leave this to no unless you have *native* IPv6. With 6to4 and
    # Terredo tunnels your web browser should favor IPv4 for the same reasons
    prefer-ip6: no

    # Use this only when you downloaded the list of primary root servers!
    # If you use the default dns-root-data package, unbound will find it automatically
    #root-hints: "/var/lib/unbound/root.hints"

    # Trust glue only if it is within the server's authority
    harden-glue: yes

    # Require DNSSEC data for trust-anchored zones, if such data is absent, the zone becomes BOGUS
    harden-dnssec-stripped: yes

    # Don't use Capitalization randomization as it known to cause DNSSEC issues sometimes
    # see https://discourse.pi-hole.net/t/unbound-stubby-or-dnscrypt-proxy/9378 for further details
    use-caps-for-id: no

    # Reduce EDNS reassembly buffer size.
    # IP fragmentation is unreliable on the Internet today, and can cause
    # transmission failures when large DNS messages are sent via UDP. Even
    # when fragmentation does work, it may not be secure; it is theoretically
    # possible to spoof parts of a fragmented DNS message, without easy
    # detection at the receiving end. Recently, there was an excellent study
    # >>> Defragmenting DNS - Determining the optimal maximum UDP response size for DNS <<<
    # by Axel Koolhaas, and Tjeerd Slokker (https://indico.dns-oarc.net/event/36/contributions/776/)
    # in collaboration with NLnet Labs explored DNS using real world data from the
    # the RIPE Atlas probes and the researchers suggested different values for
    # IPv4 and IPv6 and in different scenarios. They advise that servers should
    # be configured to limit DNS messages sent over UDP to a size that will not
    # trigger fragmentation on typical network links. DNS servers can switch
    # from UDP to TCP when a DNS response is too big to fit in this limited
    # buffer size. This value has also been suggested in DNS Flag Day 2020.
    edns-buffer-size: 1232

    # Perform prefetching of close to expired message cache entries
    # This only applies to domains that have been frequently queried
    prefetch: yes

    # One thread should be sufficient, can be increased on beefy machines. In reality for most users running on small networks or on a single machine, it should be unnecessary to seek performance enhancement by increasing num-threads above 1.
    num-threads: 1

    # Ensure kernel buffer is large enough to not lose messages in traffic spikes
    so-rcvbuf: 1m

    # Ensure privacy of local IP ranges
    private-address: 192.168.0.0/16
    private-address: 169.254.0.0/16
    private-address: 172.16.0.0/12
    private-address: 10.0.0.0/8
    private-address: fd00::/8
    private-address: fe80::/10
```

Finally, this is a log of when I do a `ping notes.viktak.cc`:
```
[1687013092] unbound[6170:0] debug: subnet[module 0] operate: extstate:module_state_initial event:module_event_new
[1687013092] unbound[6170:0] info: subnet operate: query notes.viktak.cc. A IN
[1687013092] unbound[6170:0] debug: validator[module 1] operate: extstate:module_state_initial event:module_event_pass
[1687013092] unbound[6170:0] info: validator operate: query notes.viktak.cc. A IN
[1687013092] unbound[6170:0] debug: iterator[module 2] operate: extstate:module_state_initial event:module_event_pass
[1687013092] unbound[6170:0] info: resolving notes.viktak.cc. A IN
[1687013092] unbound[6170:0] info: resolving (init part 2):  notes.viktak.cc. A IN
[1687013092] unbound[6170:0] info: resolving (init part 3):  notes.viktak.cc. A IN
[1687013092] unbound[6170:0] info: processQueryTargets: notes.viktak.cc. A IN
[1687013092] unbound[6170:0] info: sending query: notes.viktak.cc. A IN
[1687013092] unbound[6170:0] debug: sending to target: <viktak.cc.> 108.162.192.159#53
[1687013092] unbound[6170:0] debug: cache memory msg=211910 rrset=668586 infra=209958 val=97575 subnet=41372
[1687013092] unbound[6170:0] debug: iterator[module 2] operate: extstate:module_wait_reply event:module_event_reply
[1687013092] unbound[6170:0] info: iterator operate: query notes.viktak.cc. A IN
[1687013092] unbound[6170:0] info: sanitize: removing extraneous answer RRset: viktak.cc. A IN
[1687013092] unbound[6170:0] info: response for notes.viktak.cc. A IN
[1687013092] unbound[6170:0] info: reply from <viktak.cc.> 108.162.192.159#53
[1687013092] unbound[6170:0] info: query response was CNAME
[1687013092] unbound[6170:0] info: resolving notes.viktak.cc. A IN
[1687013092] unbound[6170:0] info: resolving (init part 2):  notes.viktak.cc. A IN
[1687013092] unbound[6170:0] info: resolving (init part 3):  notes.viktak.cc. A IN
[1687013092] unbound[6170:0] info: processQueryTargets: notes.viktak.cc. A IN
[1687013092] unbound[6170:0] info: sending query: viktak.cc. A IN
[1687013092] unbound[6170:0] debug: sending to target: <viktak.cc.> 173.245.58.159#53
[1687013092] unbound[6170:0] debug: cache memory msg=211910 rrset=668586 infra=209958 val=97575 subnet=41372
[1687013092] unbound[6170:0] debug: iterator[module 2] operate: extstate:module_wait_reply event:module_event_reply
[1687013092] unbound[6170:0] info: iterator operate: query notes.viktak.cc. A IN
[1687013092] unbound[6170:0] info: iterator operate: chased to viktak.cc. A IN
[1687013092] unbound[6170:0] debug: sanitize: removing public name with private address <viktak.cc.> 192.168.123.47#53
[1687013092] unbound[6170:0] info: response for notes.viktak.cc. A IN
[1687013092] unbound[6170:0] info: reply from <viktak.cc.> 173.245.58.159#53
[1687013092] unbound[6170:0] info: query response was nodata ANSWER
[1687013092] unbound[6170:0] info: finishing processing for notes.viktak.cc. A IN
[1687013092] unbound[6170:0] debug: validator[module 1] operate: extstate:module_wait_module event:module_event_moddone
[1687013092] unbound[6170:0] info: validator operate: query notes.viktak.cc. A IN
[1687013092] unbound[6170:0] debug: subnet[module 0] operate: extstate:module_wait_module event:module_event_moddone
[1687013092] unbound[6170:0] info: subnet operate: query notes.viktak.cc. A IN
[1687013092] unbound[6170:0] debug: cache memory msg=211910 rrset=668586 infra=209958 val=97575 subnet=41372
```
Thanks for any pointers in advance!

**Comment by gthess** [comment]
Hi,
you are using `private-address:` to protect against DNS rebinding attacks, but you also return A/AAAA answers for these networks from your domain. Try using `private-domain: viktak.cc` which will allow private address space for that domain.

**Comment by viktak** [comment]
First of all, thanks for your suggestion.
If you mean to simply add that line to the end of my config, I just tried it, but it still doesn't work. :(  Maybe I misunderstood something?

**Comment by gthess** [comment]
Did you restart Unbound/pi-hole for the configuration to be picked up? Is this the same setup that produced the output above? If so can you attach the new log?
For other hosts reaching this Unbound you would need to define another interface with the host's address and enable access with something like `access-control: 192.168.0.0/16 allow` if that is your network's space, by default Unbound only allows localhost connections. But I believe you already contact Unbound through pi-hole so that shouldn't be a problem. Do other hosts in your network get DNS answers (ignoring your domain in question)?

**Comment by viktak** [comment]
Yes, I restarted Unbound. It is the same setup.
Other hosts behave exactly the same way, i.e. yehy can't find the hosts. My network is 192.168.123.0/24 but I guess, the setting in the conf file `192.168.0.0/16` should be OK.
So far the only way I could get my hosts working is to define the `List of local DNS domains` in PiHole.

**Comment by gthess** [comment]
From your log output above:
```
[1687013092] unbound[6170:0] debug: sanitize: removing public name with private address <viktak.cc.> 192.168.123.47#53
```
That problem should be solved with `private-domain: viktak.cc`.

I am not sure what happens with the hosts problem. Testing again with the new configuration and capturing the log could give more insight.

It could also be useful for debugging to have Unbound listen to something like `interface: 192.168.123.x` and then from a client you could do `dig @192.168.123.x -p 5335 notes.viktak.cc`. This will bypass pi-hole and we can see what happens with Unbound.

**Comment by viktak** [comment]
Indeed, the problem with `removing public name with private address..` seems to be solved.

`dig @192.168.123.3 -p 5335 notes.viktak.cc` gives the following result:
```
pi@pihole:~ $ dig @192.168.123.3 -p 5335 notes.viktak.cc

; <<>> DiG 9.16.37-Raspbian <<>> @192.168.123.3 -p 5335 notes.viktak.cc
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached
```
and produces this in the logs:
```
[1687080464] unbound[6170:0] debug: subnet[module 0] operate: extstate:module_state_initial event:module_event_new
[1687080464] unbound[6170:0] info: subnet operate: query notes.viktak.cc. A IN
[1687080464] unbound[6170:0] debug: validator[module 1] operate: extstate:module_state_initial event:module_event_pass
[1687080464] unbound[6170:0] info: validator operate: query notes.viktak.cc. A IN
[1687080464] unbound[6170:0] debug: iterator[module 2] operate: extstate:module_state_initial event:module_event_pass
[1687080464] unbound[6170:0] info: resolving notes.viktak.cc. A IN
[1687080464] unbound[6170:0] info: resolving (init part 2):  notes.viktak.cc. A IN
[1687080464] unbound[6170:0] info: resolving (init part 3):  notes.viktak.cc. A IN
[1687080464] unbound[6170:0] info: processQueryTargets: notes.viktak.cc. A IN
[1687080464] unbound[6170:0] info: sending query: notes.viktak.cc. A IN
[1687080464] unbound[6170:0] debug: sending to target: <viktak.cc.> 108.162.192.159#53
[1687080464] unbound[6170:0] debug: cache memory msg=549744 rrset=1449422 infra=546112 val=164017 subnet=41372
[1687080464] unbound[6170:0] debug: iterator[module 2] operate: extstate:module_wait_reply event:module_event_reply
[1687080464] unbound[6170:0] info: iterator operate: query notes.viktak.cc. A IN
[1687080464] unbound[6170:0] info: sanitize: removing extraneous answer RRset: viktak.cc. A IN
[1687080464] unbound[6170:0] info: response for notes.viktak.cc. A IN
[1687080464] unbound[6170:0] info: reply from <viktak.cc.> 108.162.192.159#53
[1687080464] unbound[6170:0] info: query response was CNAME
[1687080464] unbound[6170:0] info: resolving notes.viktak.cc. A IN
[1687080464] unbound[6170:0] info: resolving (init part 2):  notes.viktak.cc. A IN
[1687080464] unbound[6170:0] info: resolving (init part 3):  notes.viktak.cc. A IN
[1687080464] unbound[6170:0] info: processQueryTargets: notes.viktak.cc. A IN
[1687080464] unbound[6170:0] info: sending query: viktak.cc. A IN
[1687080464] unbound[6170:0] debug: sending to target: <viktak.cc.> 108.162.195.152#53
[1687080464] unbound[6170:0] debug: cache memory msg=549744 rrset=1449422 infra=546112 val=164017 subnet=41372
[1687080464] unbound[6170:0] debug: iterator[module 2] operate: extstate:module_wait_reply event:module_event_reply
[1687080464] unbound[6170:0] info: iterator operate: query notes.viktak.cc. A IN
[1687080464] unbound[6170:0] info: iterator operate: chased to viktak.cc. A IN
[1687080464] unbound[6170:0] debug: sanitize: removing public name with private address <viktak.cc.> 192.168.123.47#53
[1687080464] unbound[6170:0] info: response for notes.viktak.cc. A IN
[1687080464] unbound[6170:0] info: reply from <viktak.cc.> 108.162.195.152#53
[1687080464] unbound[6170:0] info: query response was nodata ANSWER
[1687080464] unbound[6170:0] info: finishing processing for notes.viktak.cc. A IN
[1687080464] unbound[6170:0] debug: validator[module 1] operate: extstate:module_wait_module event:module_event_moddone
[1687080464] unbound[6170:0] info: validator operate: query notes.viktak.cc. A IN
[1687080464] unbound[6170:0] debug: subnet[module 0] operate: extstate:module_wait_module event:module_event_moddone
[1687080464] unbound[6170:0] info: subnet operate: query notes.viktak.cc. A IN
[1687080464] unbound[6170:0] debug: cache memory msg=549744 rrset=1449422 infra=546112 val=164017 subnet=41372
[1687080472] unbound[6170:0] debug: subnet[module 0] operate: extstate:module_state_initial event:module_event_new

```

**Comment by viktak** [comment]
Ah, one more thing: when I put `interface: 192.168.123.3` in the config file, the whole network came to a stand still... I had to revert it immediately, as others are working on it at the moment... I don't understand why it would do that...

**Comment by gthess** [comment]
I wasn't crystal clear on my previous message. I meant to say to have Unbound *also* listen on 192.168.123.3. That means having two distinct `interface:` options. What may have happened in your case is Unbound would not listen to 127.0.0.1 anymore rendering pi-hole unable to resolve anything.

Also in the new log output I still see the offending line. Are you sure that Unbound is restarted? Or that the configuration is the correct one?

**Comment by viktak** [comment]
Ah yes, I can see it now too... I don't know how I missed it... Anyway, yes, it is the correct conf file and yes, it is always restarted. I know these, because every time I make a change I need to change the logging option to log (4) or not (0).

OK, now using both interfaces, the result is a bit different, but still not resolving.

My config file:
```
server:
    # If no logfile is specified, syslog is used
    logfile: "/var/log/unbound/unbound.log"
    verbosity: 4

    interface: 127.0.0.1
    interface: 192.168.123.3
    port: 5335
    do-ip4: yes
    do-udp: yes
    do-tcp: yes

    # May be set to yes if you have IPv6 connectivity
    do-ip6: no

    # You want to leave this to no unless you have *native* IPv6. With 6to4 and
    # Terredo tunnels your web browser should favor IPv4 for the same reasons
    prefer-ip6: no

    # Use this only when you downloaded the list of primary root servers!
    # If you use the default dns-root-data package, unbound will find it automatically
    #root-hints: "/var/lib/unbound/root.hints"

    # Trust glue only if it is within the server's authority
    harden-glue: yes

    # Require DNSSEC data for trust-anchored zones, if such data is absent, the zone becomes BOGUS
    harden-dnssec-stripped: yes

    # Don't use Capitalization randomization as it known to cause DNSSEC issues sometimes
    # see https://discourse.pi-hole.net/t/unbound-stubby-or-dnscrypt-proxy/9378 for further details
    use-caps-for-id: no

    # Reduce EDNS reassembly buffer size.
    # IP fragmentation is unreliable on the Internet today, and can cause
    # transmission failures when large DNS messages are sent via UDP. Even
    # when fragmentation does work, it may not be secure; it is theoretically
    # possible to spoof parts of a fragmented DNS message, without easy
    # detection at the receiving end. Recently, there was an excellent study
    # >>> Defragmenting DNS - Determining the optimal maximum UDP response size for DNS <<<
    # by Axel Koolhaas, and Tjeerd Slokker (https://indico.dns-oarc.net/event/36/contributions/776/)
    # in collaboration with NLnet Labs explored DNS using real world data from the
    # the RIPE Atlas probes and the researchers suggested different values for
    # IPv4 and IPv6 and in different scenarios. They advise that servers should
    # be configured to limit DNS messages sent over UDP to a size that will not
    # trigger fragmentation on typical network links. DNS servers can switch
    # from UDP to TCP when a DNS response is too big to fit in this limited
    # buffer size. This value has also been suggested in DNS Flag Day 2020.
    edns-buffer-size: 1232

    # Perform prefetching of close to expired message cache entries
    # This only applies to domains that have been frequently queried
    prefetch: yes

    # One thread should be sufficient, can be increased on beefy machines. In reality for most users running on small networks or on a single machine, it should be unnecessary to seek performance enhancement by increasing num-threads above 1.
    num-threads: 1

    # Ensure kernel buffer is large enough to not lose messages in traffic spikes
    so-rcvbuf: 1m

    # Ensure privacy of local IP ranges
    private-address: 192.168.0.0/16
    private-address: 169.254.0.0/16
    private-address: 172.16.0.0/12
    private-address: 10.0.0.0/8
    private-address: fd00::/8
    private-address: fe80::/10

    private-domain: viktak.cc
```

The command:
```
pi@pihole:~ $ ping notes.viktak.cc
ping: notes.viktak.cc: Temporary failure in name resolution
```

The logs:
```
[1687080464] unbound[6170:0] info: subnet operate: query notes.viktak.cc. A IN
[1687080464] unbound[6170:0] debug: validator[module 1] operate: extstate:module_state_initial event:module_event_pass
[1687080464] unbound[6170:0] info: validator operate: query notes.viktak.cc. A IN
[1687080464] unbound[6170:0] debug: iterator[module 2] operate: extstate:module_state_initial event:module_event_pass
[1687080464] unbound[6170:0] info: resolving notes.viktak.cc. A IN
[1687080464] unbound[6170:0] info: resolving (init part 2):  notes.viktak.cc. A IN
[1687080464] unbound[6170:0] info: resolving (init part 3):  notes.viktak.cc. A IN
[1687080464] unbound[6170:0] info: processQueryTargets: notes.viktak.cc. A IN
[1687080464] unbound[6170:0] info: sending query: notes.viktak.cc. A IN
[1687080464] unbound[6170:0] debug: sending to target: <viktak.cc.> 108.162.192.159#53
[1687080464] unbound[6170:0] debug: cache memory msg=549744 rrset=1449422 infra=546112 val=164017 subnet=41372
[1687080464] unbound[6170:0] debug: iterator[module 2] operate: extstate:module_wait_reply event:module_event_reply
[1687080464] unbound[6170:0] info: iterator operate: query notes.viktak.cc. A IN
[1687080464] unbound[6170:0] info: sanitize: removing extraneous answer RRset: viktak.cc. A IN
[1687080464] unbound[6170:0] info: response for notes.viktak.cc. A IN
[1687080464] unbound[6170:0] info: reply from <viktak.cc.> 108.162.192.159#53
[1687080464] unbound[6170:0] info: query response was CNAME
[1687080464] unbound[6170:0] info: resolving notes.viktak.cc. A IN
[1687080464] unbound[6170:0] info: resolving (init part 2):  notes.viktak.cc. A IN
[1687080464] unbound[6170:0] info: resolving (init part 3):  notes.viktak.cc. A IN
[1687080464] unbound[6170:0] info: processQueryTargets: notes.viktak.cc. A IN
[1687080464] unbound[6170:0] info: sending query: viktak.cc. A IN
[1687080464] unbound[6170:0] debug: sending to target: <viktak.cc.> 108.162.195.152#53
[1687080464] unbound[6170:0] debug: cache memory msg=549744 rrset=1449422 infra=546112 val=164017 subnet=41372
[1687080464] unbound[6170:0] debug: iterator[module 2] operate: extstate:module_wait_reply event:module_event_reply
[1687080464] unbound[6170:0] info: iterator operate: query notes.viktak.cc. A IN
[1687080464] unbound[6170:0] info: iterator operate: chased to viktak.cc. A IN
[1687080464] unbound[6170:0] debug: sanitize: removing public name with private address <viktak.cc.> 192.168.123.47#53
[1687080464] unbound[6170:0] info: response for notes.viktak.cc. A IN
[1687080464] unbound[6170:0] info: reply from <viktak.cc.> 108.162.195.152#53
[1687080464] unbound[6170:0] info: query response was nodata ANSWER
[1687080464] unbound[6170:0] info: finishing processing for notes.viktak.cc. A IN
[1687080464] unbound[6170:0] debug: validator[module 1] operate: extstate:module_wait_module event:module_event_moddone
[1687080464] unbound[6170:0] info: validator operate: query notes.viktak.cc. A IN
[1687080464] unbound[6170:0] debug: subnet[module 0] operate: extstate:module_wait_module event:module_event_moddone
[1687080464] unbound[6170:0] info: subnet operate: query notes.viktak.cc. A IN
[1687080464] unbound[6170:0] debug: cache memory msg=549744 rrset=1449422 infra=546112 val=164017 subnet=41372
[1687080472] unbound[6170:0] debug: subnet[module 0] operate: extstate:module_state_initial event:module_event_new
[1687080472] unbound[6170:0] info: subnet operate: query telematics.oasa.gr. A IN
[1687080472] unbound[6170:0] debug: validator[module 1] operate: extstate:module_state_initial event:module_event_pass
[1687080472] unbound[6170:0] info: validator operate: query telematics.oasa.gr. A IN
```

Command:
```
pi@pihole:~ $ dig @192.168.123.3 -p 5335 notes.viktak.cc

; <<>> DiG 9.16.37-Raspbian <<>> @192.168.123.3 -p 5335 notes.viktak.cc
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: REFUSED, id: 53876
;; flags: qr rd ad; QUERY: 0, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; Query time: 0 msec
;; SERVER: 192.168.123.3#5335(192.168.123.3)
;; WHEN: Mon Jun 19 16:12:37 EEST 2023
;; MSG SIZE  rcvd: 12
```

Log:
```
[1687080441] unbound[6170:0] info: subnet operate: query www.ertecho.gr. TYPE65 IN
[1687080441] unbound[6170:0] debug: cache memory msg=549744 rrset=1449422 infra=546112 val=164017 subnet=41372
[1687080464] unbound[6170:0] debug: subnet[module 0] operate: extstate:module_state_initial event:module_event_new
[1687080464] unbound[6170:0] info: subnet operate: query notes.viktak.cc. A IN
[1687080464] unbound[6170:0] debug: validator[module 1] operate: extstate:module_state_initial event:module_event_pass
[1687080464] unbound[6170:0] info: validator operate: query notes.viktak.cc. A IN
[1687080464] unbound[6170:0] debug: iterator[module 2] operate: extstate:module_state_initial event:module_event_pass
[1687080464] unbound[6170:0] info: resolving notes.viktak.cc. A IN
[1687080464] unbound[6170:0] info: resolving (init part 2):  notes.viktak.cc. A IN
[1687080464] unbound[6170:0] info: resolving (init part 3):  notes.viktak.cc. A IN
[1687080464] unbound[6170:0] info: processQueryTargets: notes.viktak.cc. A IN
[1687080464] unbound[6170:0] info: sending query: notes.viktak.cc. A IN
[1687080464] unbound[6170:0] debug: sending to target: <viktak.cc.> 108.162.192.159#53
[1687080464] unbound[6170:0] debug: cache memory msg=549744 rrset=1449422 infra=546112 val=164017 subnet=41372
[1687080464] unbound[6170:0] debug: iterator[module 2] operate: extstate:module_wait_reply event:module_event_reply
[1687080464] unbound[6170:0] info: iterator operate: query notes.viktak.cc. A IN
[1687080464] unbound[6170:0] info: sanitize: removing extraneous answer RRset: viktak.cc. A IN
[1687080464] unbound[6170:0] info: response for notes.viktak.cc. A IN
[1687080464] unbound[6170:0] info: reply from <viktak.cc.> 108.162.192.159#53
[1687080464] unbound[6170:0] info: query response was CNAME
[1687080464] unbound[6170:0] info: resolving notes.viktak.cc. A IN
[1687080464] unbound[6170:0] info: resolving (init part 2):  notes.viktak.cc. A IN
[1687080464] unbound[6170:0] info: resolving (init part 3):  notes.viktak.cc. A IN
[1687080464] unbound[6170:0] info: processQueryTargets: notes.viktak.cc. A IN
[1687080464] unbound[6170:0] info: sending query: viktak.cc. A IN
[1687080464] unbound[6170:0] debug: sending to target: <viktak.cc.> 108.162.195.152#53
[1687080464] unbound[6170:0] debug: cache memory msg=549744 rrset=1449422 infra=546112 val=164017 subnet=41372
[1687080464] unbound[6170:0] debug: iterator[module 2] operate: extstate:module_wait_reply event:module_event_reply
[1687080464] unbound[6170:0] info: iterator operate: query notes.viktak.cc. A IN
[1687080464] unbound[6170:0] info: iterator operate: chased to viktak.cc. A IN
[1687080464] unbound[6170:0] debug: sanitize: removing public name with private address <viktak.cc.> 192.168.123.47#53
[1687080464] unbound[6170:0] info: response for notes.viktak.cc. A IN
[1687080464] unbound[6170:0] info: reply from <viktak.cc.> 108.162.195.152#53
[1687080464] unbound[6170:0] info: query response was nodata ANSWER
[1687080464] unbound[6170:0] info: finishing processing for notes.viktak.cc. A IN
[1687080464] unbound[6170:0] debug: validator[module 1] operate: extstate:module_wait_module event:module_event_moddone
[1687080464] unbound[6170:0] info: validator operate: query notes.viktak.cc. A IN
[1687080464] unbound[6170:0] debug: subnet[module 0] operate: extstate:module_wait_module event:module_event_moddone
[1687080464] unbound[6170:0] info: subnet operate: query notes.viktak.cc. A IN
[1687080464] unbound[6170:0] debug: cache memory msg=549744 rrset=1449422 infra=546112 val=164017 subnet=41372
[1687080472] unbound[6170:0] debug: subnet[module 0] operate: extstate:module_state_initial event:module_event_new
[1687080472] unbound[6170:0] info: subnet operate: query telematics.oasa.gr. A IN
```

**Comment by gthess** [comment]
For the following output when quering Unbound directly with `dig`, you are refused
```
;; ->>HEADER<<- opcode: QUERY, status: REFUSED, id: 53876
```
which can be fixed by adding
```
access-control: 192.168.123.0/24 allow
```
to allow access from your local network.

As for the log output I still see the offending line and I have no more leads from what I see.
By the way, here I can not reproduce the issue. I get the same behavior as you when I don't specify `private-domain`, and when I do Unbound is returning the answer.

Maybe there are other files in the `/etc/unbound/unbound.conf.d` directory?
Could you post the contents of the `/etc/unbound/unbound.conf` file?

**Comment by viktak** [comment]
I added the `allow` line to the config. That fixed the `dig` issue as you said it:
```
pi@pihole:~ $ dig @192.168.123.3 -p 5335 notes.viktak.cc

; <<>> DiG 9.16.37-Raspbian <<>> @192.168.123.3 -p 5335 notes.viktak.cc
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 37714
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;notes.viktak.cc.               IN      A

;; ANSWER SECTION:
notes.viktak.cc.        300     IN      CNAME   viktak.cc.
viktak.cc.              300     IN      A       192.168.123.47

;; Query time: 270 msec
;; SERVER: 192.168.123.3#5335(192.168.123.3)
;; WHEN: Mon Jun 19 17:42:41 EEST 2023
;; MSG SIZE  rcvd: 74
```

These are the contents of `/etc/unbound/unbound.conf.d`:
```
pi@pihole:~ $ ls -l /etc/unbound/unbound.conf.d
total 12
-rw-r--r-- 1 root root 3149 Jun 19 17:35 pi-hole.conf
-rw-r--r-- 1 root root  136 Nov  1  2022 resolvconf_resolvers.conf.bak
-rw-r--r-- 1 root root  190 Feb 10  2021 root-auto-trust-anchor-file.conf
```

`/etc/unbound/unbound.conf`:
```
pi@pihole:~ $ sudo cat /etc/unbound/unbound.conf
# Unbound configuration file for Debian.
#
# See the unbound.conf(5) man page.
#
# See /usr/share/doc/unbound/examples/unbound.conf for a commented
# reference config file.
#
# The following line includes additional configuration files from the
# /etc/unbound/unbound.conf.d directory.
include-toplevel: "/etc/unbound/unbound.conf.d/*.conf"
```

**Comment by gthess** [comment]
The `dig` output shows that Unbound resolves the domain and gives back the answer now with the correct configuration.
The rest of the issue seems to be pi-hole and local network configuration related; I can't comment further on those.

**Comment by viktak** [comment]
Alright, thank you very much for your help!!!!!
